export const actionNames = {
  login: "LOGIN",
  loggedIn: "LOGGED_IN",
  loginFailed: "LOGIN_FAILED",
  saveSession: "SAVE_SESSION",
  deleteSession: "DELETE_SESSION",
  loginError: "LOGIN_ERROR",
  renewToken: "RENEW_TOKEN",
  checkRoles: "CHECK_ROLES",

  showCreateProductModal: "SHOW_CREATE_PRODUCT_MODAL",
  showUpdateProductModal: "SHOW_UPDATE_PRODUCT_MODAL",
  closeModal: "CLOSE_MODAL",

  loadFilters: "LOAD_FILTERS",
  search: "SEARCH",
  seeDetails: "SEE_DETAILS",
  showDetails: "SHOW_DETAILS",
  selectedCategory: "SELECTED_CATEGORY",

  showOnWebsite: "SHOW_ON_WEBSITE",
  listProducts: "LIST_PRODUCTS",

  loadingToggle: "LOADING_TOGGLE",
  closeNotification: "CLOSE_NOTIFICATION",
  showNotification: "SHOW_NOTIFICATION",

  showChangePasswordModal: "SHOW_CHANGE_PASSWORD_MODAL",
  closeChangePasswordModal: "CLOSE_CHANGE_PASSWORD_MODAL",
  changePassword: "CHANGE_PASSWORD",
  passwordChangedSuccessfully: "PASSWORD_CHANGED_SUCCESSFULLY",
  passwordChangedFail: "PASSWORD_CHANGED_FAIL",

  loadFiltersSuccesful: "LOAD_FILTERS_SUCCESFUL",
  loadProductsByFilterSuccesful: "LOAD_PRODUCTS_BY_FILTER_SUCCESFUL",
  loadProductsByFilterFail: "LOAD_PRODUCTS_BY_FILTER_FAIL",
  loadProductsWithDetailsSuccesful: "LOAD_PRODUCT_WITH_DETAILS_SUCCESFUL",
  loadProductWithDetailsFail: "LOAD_PRODUCT_WITH_DETAILS_FAIL",
  loadFiltersFail: "LOAD_FILTERS_FAIL",

  selectSearchPage: "SELECT_SEARCH_PAGE",
  nextSearchPage: "NEXT_SEARCH_PAGE",
  previousSearchPage: "PREVIOUS_SEARCH_PAGE",

  handleError: "HANDLE_ERROR",
  productNeedUpdated: "PRODUCTS_NEED_UPDATED",

  nextProductsPage: "NEXT_PRODUCTS_PAGE",
  selectProductPage: "SELECT_PRODUCTS_PAGE",
  previousProductsPage: "PREVIOUS_PRODUCTS_PAGE",

  createProduct: "CREATE_PRODUCT",
  updateProduct: "UPDATE_PRODUCT",
  productCreatedFail: "PRODUCT_CREATED_FAIL",
  productCreatedSuccessfully: "PRODUCT_CREATED_SUCCESSFULLY",
  productUpdatedFail: "PRODUCT_UPDATE_FAIL",
  productUpdatedSuccessfully: "PRODUCT_UPDATE_SUCCESSFULLY",
  loadProductSuccessful: "LOAD_PRODUCT_SUCCESSFUL",
  loadProductFail: "LOAD_PRODUCT_FAIL",
  loadProductsSuccessful: "LOAD_PRODUCTS_SUCCESSFUL",
  loadProductsFail: "LOAD_PRODUCTS_FAIL",
  showViewModal: "SHOW_VIEW_MODAL",

  getProductByUuid: "GET_PRODUCT_BY_UUID",

  listEmployees: "LIST_EMPLOYEES",
  showCreateEmployeeModal: "SHOW_CREATE_EMPLOYEE_MODAL",
  previousEmployeePage: "PREVIOUS_EMPLOYEE_PAGE",
  selectEmployeePage: "SELECT_EMPLOYEE_PAGE",
  nextEmployeePage: "NEXT_EMPLOYEE_PAGE",
  getEmployeeById: "GET_EMPLOYEE_BY_ID",
  completeEmployee: "COMPLETE_EMPLOYEE",
  seeEmployeeDetails: "SEE_EMPLOYEE_DETAILS",
  createEmployee: "CREATE_EMPLOYEE",
  updateEmployee: "UPDATE_EMPLOYEE",
  showUpdateEmployeeModal: "SHOW_UPDATE_EMPLOYEE_MODAL",
  employeeCreatedSuccessfully: "EMPLOYEE_CREATED_SUCCESSFULLY",
  employeeCreatedFail: "EMPLOYEE_CREATED_FAIL",
  employeeUpdatedSuccessfully: "EMPLOYEE_UPDATED_SUCCESSFULLY",
  employeeUpdatedFail: "EMPLOYEE_UPDATED_FAIL",
  loadEmployeeSuccessful: "LOAD_EMPLOYEE_SUCCESSFULLY",
  loadEmployeeFail: "LOAD_EMPLOYEE_FAIL",
  loadEmployeesSuccessful: "LOAD_EMPLOYEES_SUCCESSFULLY",
  loadEmployeesFail: "LOAD_EMPLOYEES_FAIL",
  checkNotifications: "CHECK_NOTIFICATIONS",
  checkNotificationsSuccessfully: "CHECK_NOTIFICATIONS_SUCCESSFULLY",
  checkNotificationsFail: "CHECK_NOTIFICATIONS_FAIL",
  changeEmployeeState: "CHANGE_EMPLOYEE_STATE",

  getCategoryById: "GET_CATEGORY_BY_ID",
  previousCategoryPage: "PREVIOUS_CATEGORY_PAGE",
  selectCategoryPage: "SELECT_CATEGORY_PAGE",
  nextCategoryPage: "NEXT_CATEGORY_PAGE",
  showCreateCategoryModal: "SHOW_CREATE_CATEGORY_MODAL",

  listCategories: "LIST_CATEGORIES",
  seeCategoryDetails: "SEE_CATEGORY_DETAILS",
  updateCategories: "UPDATE_CATEGORIES",
  showUpdateCategoryModal: "SHOW_UPDATE_CATEGORY_MODAL",
  loadCategoriesSuccessful: "LOAD_CATEGORIES_SUCCESSFULLY",
  loadCategoriesFail: "LOAD_CATEGORIES_FAIL",
  createCategory: "CREATE_CATEGORY",
  updateCategory: "UPDATE_CATEGORY",

  listBrands: "LIST_BRANDS",
  showCreateBrandModal: "SHOW_CREATE_BRAND_MODAL",
  showUpdateBrandModal: "SHOW_UPDATE_BRAND_MODAL",
  previousBrandsPage: "PREVIOUS_BRANDS_PAGE",
  selectBrandPage: "SELECT_BRAND_PAGE",
  nextBrandPage: "NEXT_BRAND_PAGE",
  updateBrand: "UPDATE_BRAND",
  createBrand: "CREATE_BRAND",
  loadBrandsSuccessfully: "LOAD_BRANDS_SUCCESSFULLY",
  loadBrandsFail: "LOAD_BRANDS_FAIL",
  createBrandSuccessfully: "CREATE_BRAND_SUCCESSFULLY",
  createBrandFail: "CREATE_BRAND_FAIL",
  updateBrandSuccessfully: "UPDATE_BRAND_SUCCESSFULLY",
  updateBrandFail: "UPDATE_BRAND_FAIL",
  createCategorySuccessfully: "CREATE_CATEGORY_SUCCESSFULLY",
  createCategoryFail: "CREATE_CATEGORY_FAIL",
  updateCategorySuccessfully: "UPDATE_CATEGORY_SUCCESSFULLY",
  updateCategoryFail: "UPDATE_CATEGORY_FAIL",
  listCustomers: "LIST_CUSTOMERS",
  showCreateCustomersModal: "SHOW_CREATE_CUSTOMER_MODAL",
  previousCustomerPage: "PREVIOUS_CUSTOMER_PAGE",
  selectCustomerPage: "SELECT_CUSTOMER_PAGE",
  nextCustomerPage: "NEXT_CUSTOMER_PAGE",
  showUpdateCustomerModal: "SHOW_UPDATE_CUSTOMER_MODAL",
  listOrders: "LIST_ORDERS",
  showCreateOrdersModal: "SHOW_CREATE_ORDER_MODAL",
  previousOrderPage: "PREVIOUS_ORDER_PAGE",
  selectOrderPage: "SELECT_ORDER_PAGE",
  nextOrderPage: "NEXT_ORDER_PAGE",
  completeOrder: "COMPLETE_ORDER",
  createOrder: "CREATE_ORDER",
  loadCustomersSuccessfully: "LOAD_CUSTOMERS_SUCCESSFULLY",
  loadCustomersFail: "LOAD_CUSTOMERS_FAIL",
  loadOrdersSuccessful: "LOAD_ORDERS_SUCCESSFULLY",
  loadOrdersFail: "LOAD_ORDERS_FAIL",
  listProviders: "LIST_PROVIDERS",
  showCreateProvidersModal: "SHOW_CREATE_PROVIDER_MODAL",
  previousProvidersPage: "PREVIOUS_PROVIDERS_PAGE",
  selectProvidersPage: "SELECT_PROVIDERS_PAGE",
  nextProvidersPage: "NEXT_PROVIDERS_PAGE",
  getProviderById: "GET_PROVIDER_BY_ID",
  completeProvider: "COMPLETE_PROVIDER",
  createProvider: "CREATE_PROVIDER",
  updateProvider: "UPDATE_PROVIDER",
  showUpdateProvidersModal: "SHOW_UPDATE_PROVIDERS_MODAL",
  loadProvidersSuccessful: "LOAD_PROVIDERS_SUCCESSFULLY",
  loadProvidersFail: "LOAD_PROVIDERS_FAIL",
  createProviderSuccessful: "CREATE_PROVIDER_SUCCESSFULLY",
  createProviderFail: "CREATE_PROVIDER_FAIL",
  updateProviderSuccessful: "UPDATE_PROVIDER_SUCCESSFULLY",
  updateProviderFail: "UPDATE_PROVIDER_FAIL",
  deleteBrand: "DELETE_BRAND",
  deleteProvider: "DELETE_PROVIDER",
  showSearchCustomerModal: "SHOW_SEARCH_CUSTOMER_MODAL",
  closeModalCustomer: "CLOSE_MODAL_SEARCH_CUSTOMER",
  searchCustomer: "SEARCH_CUSTOMERS",
  selectedUser: "SELECTED_USER",
  getCustomerByOrderSuccessfully: "GET_CUSTOMER_BY_ORDER_SUCCESSFULLY",
  getCustomerByOrderFail: "GET_CUSTOMER_BY_ORDER_FAIL",

  addProductToCart: "ADD_PRODUCT_TO_CART",
  removeProductFromCart: "REMOVE_PRODUCT_FROM_CART",
  addProductQuantityFromCart: "ADD_PRODUCT_QUANTITY_FROM_CART",
  removeProductQuantityFromCart: "REMOVE_PRODUCT_QUANTITY_FROM_CART",
  addProductQuantityFromCartSuccessfully:
    "ADD_PRODUCT_QUANTITY_FROM_CART_SUCCESSFULLY",
  removeProductQuantityFromCartSuccessfully:
    "REMOVE_PRODUCT_QUANTITY_FROM_CART_SUCCESSFULLY",
  addProductToCartSuccessfully: "ADD_PRODUCT_TO_CART_SUCCESSFULLY",
  loadProductsFromShoppingCart: "LOAD_PRODUCTS_FROM_CART",
  loadProductsFromShoppingCartSuccessfully:
    "LOAD_PRODUCTS_FROM_CART_SUCCESSFULLY",
  loadProductsFromShoppingCartFail: "LOAD_PRODUCTS_FROM_CART_FAIL",
  updateProductImage: "UPDATE_PRODUCT_IMAGE"
};
