export const actionNames = {
  login: "LOGIN",
  loggedIn: "LOGGED_IN",
  loginFailed: "LOGIN_FAILED",
  saveSession: "SAVE_SESSION",
  deleteSession: "DELETE_SESSION",
  loginError: "LOGIN_ERROR",
  renewToken: "RENEW_TOKEN",
  checkRoles: "CHECK_ROLES",

  showCreateProductModal: "SHOW_CREATE_PRODUCT_MODAL",
  showUpdateProductModal: "SHOW_UPDATE_PRODUCT_MODAL",
  closeModal: "CLOSE_MODAL",

  loadFilters: "LOAD_FILTERS",
  search: "SEARCH",
  seeDetails: "SEE_DETAILS",
  showDetails: "SHOW_DETAILS",
  selectedCategory: "SELECTED_CATEGORY",

  showOnWebsite: "SHOW_ON_WEBSITE",
  listProducts: "LIST_PRODUCTS",

  loadingToggle: "LOADING_TOGGLE",
  closeNotification: "CLOSE_NOTIFICATION",
  showNotification: "SHOW_NOTIFICATION",

  showChangePasswordModal: "SHOW_CHANGE_PASSWORD_MODAL",
  closeChangePasswordModal: "CLOSE_CHANGE_PASSWORD_MODAL",
  changePassword: "CHANGE_PASSWORD",
  passwordChangedSuccessfully: "PASSWORD_CHANGED_SUCCESSFULLY",
  passwordChangedFail: "PASSWORD_CHANGED_FAIL",

  loadFiltersSuccesful: "LOAD_FILTERS_SUCCESFUL",
  loadProductsByFilterSuccesful: "LOAD_PRODUCTS_BY_FILTER_SUCCESFUL",
  loadProductsByFilterFail: "LOAD_PRODUCTS_BY_FILTER_FAIL",
  loadProductsWithDetailsSuccesful: "LOAD_PRODUCT_WITH_DETAILS_SUCCESFUL",
  loadProductWithDetailsFail: "LOAD_PRODUCT_WITH_DETAILS_FAIL",
  loadFiltersFail: "LOAD_FILTERS_FAIL",

  selectSearchPage: "SELECT_SEARCH_PAGE",
  nextSearchPage: "NEXT_SEARCH_PAGE",
  previousSearchPage: "PREVIOUS_SEARCH_PAGE",

  handleError: "HANDLE_ERROR",
  productNeedUpdated: "PRODUCTS_NEED_UPDATED",

  nextProductsPage: "NEXT_PRODUCTS_PAGE",
  selectProductPage: "SELECT_PRODUCTS_PAGE",
  previousProductsPage: "PREVIOUS_PRODUCTS_PAGE",

  createProduct: "CREATE_PRODUCT",
  updateProduct: "UPDATE_PRODUCT",
  productCreatedFail: "PRODUCT_CREATED_FAIL",
  productCreatedSuccessfully: "PRODUCT_CREATED_SUCCESSFULLY",
  productUpdatedFail: "PRODUCT_UPDATE_FAIL",
  productUpdatedSuccessfully: "PRODUCT_UPDATE_SUCCESSFULLY",
  loadProductSuccessful: "LOAD_PRODUCT_SUCCESSFUL",
  loadProductFail: "LOAD_PRODUCT_FAIL",
  loadProductsSuccessful: "LOAD_PRODUCTS_SUCCESSFUL",
  loadProductsFail: "LOAD_PRODUCTS_FAIL",
  showViewModal: "SHOW_VIEW_MODAL",

  getProductByUuid: "GET_PRODUCT_BY_UUID",
  listEmployees: "LIST_EMPLOYEES",
  showCreateEmployeeModal: "SHOW_CREATE_EMPLOYEE_MODAL",
  previousEmployeePage: "PREVIOUS_EMPLOYEE_PAGE",
  selectEmployeePage: "SELECT_EMPLOYEE_PAGE",
  nextEmployeePage: "NEXT_EMPLOYEE_PAGE",
  getEmployeeById: "GET_EMPLOYEE_BY_ID",
  completeEmployee: "COMPLETE_EMPLOYEE",
  seeEmployeeDetails: "SEE_EMPLOYEE_DETAILS",
  createEmployee: "CREATE_EMPLOYEE",
  updateEmployee: "UPDATE_EMPLOYEE",
  showUpdateEmployeeModal: "SHOW_UPDATE_EMPLOYEE_MODAL",
  employeeCreatedSuccessfully: "EMPLOYEE_CREATED_SUCCESSFULLY",
  employeeCreatedFail: "EMPLOYEE_CREATED_FAIL",
  employeeUpdatedSuccessfully: "EMPLOYEE_UPDATED_SUCCESSFULLY",
  employeeUpdatedFail: "EMPLOYEE_UPDATED_FAIL",
  loadEmployeeSuccessful: "LOAD_EMPLOYEE_SUCCESSFULLY",
  loadEmployeeFail: "LOAD_EMPLOYEE_FAIL",
  loadEmployeesSuccessful: "LOAD_EMPLOYEES_SUCCESSFULLY",
  loadEmployeesFail: "LOAD_EMPLOYEES_FAIL",
  checkNotifications: "CHECK_NOTIFICATIONS",
  checkNotificationsSuccessfully: "CHECK_NOTIFICATIONS_SUCCESSFULLY",
  checkNotificationsFail: "CHECK_NOTIFICATIONS_FAIL",
};
